const GOOGLE_API_KEY = "ADD_YOUR_KEY";

export const YT_API = `ADD_YOUTUBE_API&key=${GOOGLE_API_KEY}`;

export const YT_SUGGESTION_API = "ADD_SEARCH_SUGGESTION_API";

export const LIVE_CHAT_COUNT = 10;
